In [1]:
import numpy as np

In [27]:
a = np.array([0,1,2,3,4,5,6,7,8]).reshape(3,3)
# a = np.arange(9).reshape(3,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [7]:
b = np.array([0,1,2,3,4,5,6,7,8,9])
for i in b:
    if(b[i]%2!=0):
        b[i] = -1
print(b)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [17]:
x = np.array([21,64,86,22,74,55,81,79,90,89])
y = np.array([21,7,3,45,10,29,55,4,37,18])
a = np.array([])
b = np.array([])
for i in range(0,len(x)):
    if(x[i]>y[i]):
        a = np.append(a,i)
    elif(x[i]==y[i]):
        b = np.append(b,i)
print(a)
print(b)

[1. 2. 4. 5. 6. 7. 8. 9.]
[0.]


In [23]:
assign4 = np.arange(100).reshape(5,-1)
ans = assign4[:,:4]
print(ans)

[[ 0  1  2  3]
 [20 21 22 23]
 [40 41 42 43]
 [60 61 62 63]
 [80 81 82 83]]
